feat: better pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,18 +1,11 @@
 #!/bin/sh
 
-# Get dependencies
-echo "Getting dependencies..."
-go get -d ./...
+# Exit immediately if a command exits with a non-zero status.
+set -e
 
-# Check if go.mod and go.sum have changes after updating dependencies
-if ! git diff --quiet -- go.mod go.sum; then
-  echo "go.mod and/or go.sum have been updated. Adding changes to the commit..."
-  git add go.mod go.sum
-fi
-
-# Run go fmt
-echo "Running go fmt..."
-go fmt ./...
+# Update dependencies
+echo "Updating dependencies..."
+make go-deps
 
 # Check if fieldalignment is installed, if not, install it
 if ! command -v fieldalignment >/dev/null 2>&1; then
@@ -20,14 +13,11 @@ if ! command -v fieldalignment >/dev/null 2>&1; then
   go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
 fi
 
-# Run fieldalignment -fix if there are any errors
+# Run fieldalignment, if it fails, exit
 echo "Running fieldalignment..."
-if ! fieldalignment ./...; then
-	echo "Running fieldalignment -fix until it exits normally..."
-	while ! fieldalignment -fix ./...; do
-	  echo "Retrying fieldalignment -fix..."
-	done
-	git add .
+if ! fieldalignment -fix ./...; then
+  echo "fieldalignment failed, please run fieldalignment -fix ./... to try to fix the errors"
+  exit 1
 fi
 
 # Proceed with the commit
